---
title: "Census Data Pull"
author: "Aaron Barrall"
date: "01/18/2023"
output: html_document
---
# Load Packages, Setup
```{r}
library(tidyverse)
library(tidycensus)
# library(spatial)
# library(sf)
set.seed(1234)
library(readxl)
rm(list=ls())

```
# Census Data Pull - 5 Year ACS City, 2021
```{r}
census_api_key("0bb4ac54f5ef401013b255be5f5c4f4d8960d00a", install=T)  #Census API key created for UCLA.

census_data <- load_variables (2021, "acs5", cache=T) #Load available data - use this to identify the table codes for the API call below.\

vars <- c (median_income="B25119_001", #median income
           housing_units="B25003_001", #Housing Units total
           renter_occupied="B25003_003", #Tenure
           population_race="B03002_001", #race/ethnic total
           race_white="B03002_003", #white NH alone
           race_black="B03002_004", #black/african american NH
           race_amindian="B03002_005", #american indian/alaska native NH
           race_asian="B03002_006", #asian NH
           race_pacisl="B03002_007", #native hawaiian and other pacific islander NH
           race_other="B03002_008", #some other race alone NH
           race_twoplus="B03002_009", #two or more races NH
           race_hisp ="B03002_012", #total Hisp any race
           median_age ="B01002_001",
           median_gross_rent = "B25111_001", #median gross rent
           total_value_estimate = "B25075_001", #Total Household value?
           estimate_median_value = "B25077_001", #Median Household Value
           uis_tot = "B25024_001", #units in structure - total
           uis_1d = "B25024_002", #units in structure - 1 detached
           uis_1a = "B25024_003", #units in structure -1 attached
           uis_2 = "B25024_004", #units in structure - 2
           uis_3.4 = "B25024_005", #units in structure - 3 to 4
           uis_5.9 = "B25024_006", #units in structure - 5 to 9
           uis_10.19 = "B25024_007", #units in structure - 10 to 19
           uis_20.49 = "B25024_008", #units in structure - 20 to 49
           uis_50 = "B25024_009", #units in structure - 50+
           uis_mobile = "B25024_010", #units in structure - mobile home
           uis_van = "B25024_011", #units in structure -  Boat, RV and Van
           total_age = "B01001_001",
           male_u5 = "B01001_003", #male under 5 years
           male5.9 = "B01001_004", #males aged 5-10
           male65.66 = "B01001_020", #males 65-66
           male67.69 = "B01001_021",#male 67 to 69 years
           male70.74 = "B01001_022",#male 70 to 74 years
           male75.79 = "B01001_023",#male 75 to 79 years
           male80.84 = "B01001_024",#male 80 to 84 years
           male85andup = "B01001_025",#male 85+
           total_female = "B01001_026", #total female (sex by age)
           female_u5 = "B01001_027", #female 0 to 4 years
           female5.9 = "B01001_028", #female 5 to 9 years
           female65.66 = "B01001_044", #female 65 to 66 years
           female67.69 = "B01001_045", #female 67 to 69 years
           female70.74 = "B01001_046", #female 70 to 74 years
           female75.79 = "B01001_047", #female 75 to 79
           female80.84 = "B01001_048", #female 80 to 84
           female85andup = "B01001_049" #female 85 and above
           )
options(tigris_use_cache=TRUE)

# acs_data_tract <-get_acs (state = "06", #California
#                  geography = "tract",
#                  variables = vars,
#                  geometry = T,
#                  survey = "acs5",
#                  output = "wide",
#                  year=2021)
# 

# acs_data_tract <- acs_data_tract[, -grep("M$", colnames(acs_data_tract))]


acs_data_city <-get_acs (state = "06", #California
                 geography = "place",
                 variables = vars,
                 geometry = T,
                 survey = "acs5",
                 output = "wide",
                 year=2021)
acs_data_city <- acs_data_city[, -grep("M$", colnames(acs_data_city))] #Drop MOE Estimates

write_csv(acs_data_city,"Output/census_direct_output_test.csv")

```
# Clean ACS Data
```{r}
# Convert UIS and Race data to Percents
# Units in Structure / tenure
acs_data_city <- acs_data_city %>% 
  mutate(uis_1d_per = uis_1dE/uis_totE) %>% 
  mutate(uis_1a_per = uis_1aE/uis_totE) %>% 
  mutate(uis_2_per = uis_2E/uis_totE) %>%
  mutate(uis_3.4_per = uis_3.4E/uis_totE) %>% 
  mutate(uis_5.9_per = uis_5.9E/uis_totE) %>% 
  mutate(uis_10.19_per = uis_10.19E/uis_totE) %>% 
  mutate(uis_20.49_per = uis_20.49E/uis_totE) %>% 
  mutate(renter_per = renter_occupiedE/housing_unitsE) %>% 
  mutate(race_white_per = race_whiteE/population_raceE) %>% 
  mutate(race_black_per = race_blackE/population_raceE) %>% 
  mutate(race_amindian_per = race_amindianE/population_raceE) %>% 
  mutate(race_asian_per = race_asianE/population_raceE) %>% 
  mutate(race_pacisl_per = race_pacislE/population_raceE) %>% 
  mutate(race_other_per = race_otherE/population_raceE) %>% 
  mutate(race_twoplus_per = race_twoplusE/population_raceE) %>% 
  mutate(race_hisp_per = race_hispE/population_raceE) %>%
  mutate(age_over_65_per = (male65.66E+male67.69E+male70.74E+male75.79E+male80.84E+male85andupE+                               female65.66E+female67.69E+female70.74E+female75.79E+female80.84E+
                              female85andupE)/total_ageE) %>% 
  mutate_at(vars(uis_1d_per:age_over_65_per),funs(. * 100)) %>%  #multiply values by 100
  mutate_at(vars(uis_1d_per:age_over_65_per),funs(round(.,3))) %>%  # Round scaled values
  mutate(totalpop=population_raceE)

  acs_data_city <- acs_data_city %>% 
    rename(
      median_income = median_incomeE,
      median_age = median_ageE,
      median_gross_rent = median_gross_rentE,
      estimate_median_value = estimate_median_valueE,
      name = NAME)

acs_data_city <- acs_data_city[, -grep("E$", colnames(acs_data_city))] #Drop remaining estimates, leaving only percent and necessary estimates

```

# Join with Existing Data
```{r}
working_data <-
  read_excel("Source - Clean/data rezonings_fromPaavo_20221213.xls")  # Data from Paavo.

working_data <-
  working_data %>% select(
    geography,
    compliantasofnovember1,
    capacity_6th,
    rezone_units,
    capacity_5th,
    share_rezone
  ) #Only need a few columns from this data

RHNA_Allocations <- 
  read_excel("Source - Clean/RHNA - Allocation.xlsx")

Places <- 
  read_excel("Source - Clean/PlaceNames.xlsx")

RHNA_Allocations <-
  RHNA_Allocations %>% mutate(geography = toupper(Jurisdiction))
Places <- Places %>% mutate(Census_name = toupper(Census_name))

acs_data_city <- acs_data_city %>% mutate(Census_name = toupper(name))

working_data <-
  working_data %>% mutate(geography = toupper(geography))

combined <-
  merge(
    Places,
    acs_data_city,
    by.x = "Census_name",
    by.y = "Census_name",
    all.x = T
  )

combined <-
  merge(
    combined,
    RHNA_Allocations,
    by.x = "City",
    by.y = "Jurisdiction")  # We Lose two here

combined <-
  merge(
    combined,
    working_data,
    by.x = "Census_name",
    by.y = "geography",
    all.x = T
  )
combined <- combined %>% select(-GEOID.x,-name) #remove unneeded columns. 

#write_csv(combined,"Output/combined_initial.csv")

```

# Data Transformation (Log)
```{r}
combined <- combined %>% 
  mutate(lnpop=log(totalpop)) %>% 
  mutate(lnhomeval=log(estimate_median_value)) %>% 
  mutate(lntotalRHNAchange = log(`6th to 5th - Total Ratio`)) %>% 
  mutate(lnlLIChange = log(`6th to 5th - Low Income Ratio`))

write_csv(combined,"Output/WorkingOutput.csv")

```

# Join with existing Data - OLD
```{r}
working_data <- read_excel("Source - Clean/data rezonings_fromPaavo_20221213.xls")
RHNA_Allocations <- read_excel("Source - Clean/RHNA - Allocation.xlsx")



# Need to clean the data first
RHNA_Allocation_City <-  RHNA_Allocations %>% 
  filter(!str_detect(Jurisdiction,"COUNTY")) %>%
  filter(!str_detect(Jurisdiction,"TOWN")) %>% 
  mutate(Jurisdiction_match = paste0(Jurisdiction," CITY, CALIFORNIA")) #Add City California to all non- county jurisdictions

#NOTE - FOR counties with TOWN - Need to add Town to the RHNA - Allocation Spreadsheet.
RHNA_Allocations_Town <-  RHNA_Allocations %>% 
  filter(str_detect(Jurisdiction,"TOWN")) %>% 
  mutate(Jurisdiction_match = paste0(Jurisdiction,", CALIFORNIA")) #For Towns, no need to add City

RHNA_Allocations_County <- RHNA_Allocations<-  RHNA_Allocations %>% 
  filter(str_detect(Jurisdiction,"COUNTY")) %>%
  mutate(Jurisdiction_match = paste0(Jurisdiction,", CALIFORNIA"))

RHNA_Allocations <-  rbind(RHNA_Allocation_City,RHNA_Allocations_Town,RHNA_Allocations_County)

working_data <- working_data %>% 
  mutate(geography = toupper(geography))

acs_data_city <- acs_data_city %>%
  mutate(geography=toupper(name))

combined <- merge(working_data,RHNA_Allocations,by.x="geography",by.y="Jurisdiction_match")
combined <- merge(combined,acs_data_city)

anti_join(working_data,RHNA_Allocations,by=c("geography"="Jurisdiction_match"))
  # For jurisdictions that don't match, identify why, and fix in the 
```
# Old Census Data Pull
```{r}

vars <- c (median_income="B25119_001", #median income --- NOTE 20221130 - THIS IS RETURNING NAS for some reason.
           housing_units="B25003_001", #Housing Units
           renter_occupied="B25003_003", #Tenure
           population_race="B03002_001", #race/ethnic total
           race_white="B03002_003", #white NH alone
           race_black="B03002_004", #black/african american NH
           race_amindian="B03002_005", #american indian/alaska native NH
           race_asian="B03002_006", #asian NH
           race_pacisl="B03002_007", #native hawaiian and other pacific islander NH
           race_other="B03002_008", #some other race alone NH
           race_twoplus="B03002_009", #two or more races NH
           race_hisp ="B03002_012" #total Hisp any race
           )

options(tigris_use_cache=TRUE)
acs_data_bg <-get_acs (state = "06", #California
                 geography = "block group",
                 variables = vars,
                 geometry = T,
                 survey = "acs5",
                 output = "wide",
                 year=2020)

#drop margin of error estimate variables (they end in the letter M)  - You can also use the function get_estimates to do this and not return any MOE data

plot(acs_data_bg["race_hispE"])


```

# Census Data Pull - Decennial Tract

```{r}
censusVars <- load_variables(2020,"decennial")  #note that not much data is out for the 2020 decennial census yet.

vars <- c (population_race="P2_001N", #race/ethnic total
           race_white="P2_005N", #white NH alone
           race_black="P2_006N", #black/african american NH
           race_amindian="P2_007N", #american indian/alaska native NH
           race_asian="P2_008N", #asian NH
           race_pacisl="P2_009N", #native hawaiian and other pacific islander NH
           race_other="P2_010N", #some other race alone NH
           race_twoplus="P2_011N", #two or more races NH
           race_hisp ="P2_002N" #total Hisp
           #totalHH = "H004001", #total households -- This is not available in the decennial census
           #renterHH = "H004004" # renterhouseholds -- This is not available in the decennial census
) 

census_data_tract <- get_decennial (state = "06", #California
                              year= 2020,
                              geography = "tract",
                              variables = vars,
                              geometry = F,
                              output = "wide")

```


